/**
 * Generates redirect output files from src/data/redirects.ts:
 *   - public/_redirects      (Cloudflare Pages / Netlify format)
 *   - public/redirects.json  (flat JSON map for Node.js middleware)
 *
 * Layout produced in public/_redirects:
 *
 *   <manual header>
 *   # === Auto-generated redirects from src/data/redirects.ts ===
 *   <auto-generated static rules>
 *   # === End auto-generated redirects ===
 *   # === Dynamic redirects ===
 *   <auto-generated splat / placeholder rules>
 *
 * All dynamic rules live in the tail block because Cloudflare Pages caps the
 * first 100 entries from the first dynamic rule — any static rules past that
 * cap are silently ignored. Keeping statics on top and dynamics at the tail
 * leaves the static zone uncapped (2000-rule max).
 *
 * Refs: https://developers.cloudflare.com/pages/configuration/redirects/
 *
 * Usage: pnpm generate:redirects
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
	CATCH_ALL_REDIRECTS,
	SINGLE_REDIRECTS,
	DYNAMIC_REDIRECTS,
	NON_DOCS_REDIRECTS,
	getAllRedirectsFlat,
} from '../src/data/redirects.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

/** Recursively find all .mdx files under a directory, returning relative paths without extension. */
function findMdxSlugs(dir: string, base: string = ''): string[] {
	const slugs: string[] = [];
	try {
		for (const entry of readdirSync(dir)) {
			const fullPath = join(dir, entry);
			const relPath = base ? `${base}/${entry}` : entry;
			if (statSync(fullPath).isDirectory()) {
				slugs.push(...findMdxSlugs(fullPath, relPath));
			} else if (entry.endsWith('.mdx')) {
				const slug = relPath.replace(/\.mdx$/, '').replace(/(?:^|\/)index$/, '');
				slugs.push(slug);
			}
		}
	} catch {
		// Directory doesn't exist
	}
	return slugs;
}

// ---------------------------------------------------------------------------
// 1. Generate public/redirects.json
// ---------------------------------------------------------------------------

const flatMap = getAllRedirectsFlat();

// Add entries for PREFIX_RENAME groups with empty entries by scanning content.
// Source of truth for prefix renames: CATCH_ALL_REDIRECTS[].newPrefix.
for (const group of CATCH_ALL_REDIRECTS) {
	if (group.entries.length > 0 || !group.newPrefix) continue;
	const contentDir = resolve(ROOT, 'src/content/docs/docs', group.newPrefix);
	const slugs = findMdxSlugs(contentDir);
	const excluded = new Set(group.excludeSlugs ?? []);
	for (const slug of slugs) {
		if (excluded.has(slug)) continue;
		const oldPath = slug ? `/docs/${group.oldPrefix}/${slug}/` : `/docs/${group.oldPrefix}/`;
		const newPath = slug ? `/docs/${group.newPrefix}/${slug}/` : `/docs/${group.newPrefix}/`;
		flatMap[oldPath] = newPath;
	}
}
const jsonPath = resolve(ROOT, 'public/redirects.json');
writeFileSync(jsonPath, JSON.stringify(flatMap, null, 2) + '\n');

const jsonCount = Object.keys(flatMap).length;
console.log(`✓ public/redirects.json — ${jsonCount} entries`);

// ---------------------------------------------------------------------------
// 2. Generate public/_redirects
// ---------------------------------------------------------------------------

const redirectsPath = resolve(ROOT, 'public/_redirects');

const STATIC_START = '# === Auto-generated redirects from src/data/redirects.ts ===';
const STATIC_END = '# === End auto-generated redirects ===';
const DYN_START = '# === Dynamic redirects ===';

// Read existing file and preserve manually-authored rules above the auto-generated section.
const existing = readFileSync(redirectsPath, 'utf-8');
const staticStartIdx = existing.indexOf(STATIC_START);
const manualHeader = (staticStartIdx >= 0 ? existing.slice(0, staticStartIdx) : existing).trimEnd();

// ---------------------------------------------------------------------------
// Build static and dynamic output blocks
// ---------------------------------------------------------------------------

const staticLines: string[] = [];
const autoDynamicGroups: { comment?: string; rules: string[] }[] = [];

// Bucket SINGLE_REDIRECTS so single-page overrides render in the static block.
// (Catch-all groups whose entries collapse into a splat are purely dynamic — any
// specific override for that prefix still belongs in the static zone so it wins
// by being earlier in the file.)
const catchAllPrefixes = CATCH_ALL_REDIRECTS.map((g) => g.oldPrefix);
const singlesByPrefix = new Map<string, typeof SINGLE_REDIRECTS>();
const remainingSingles: typeof SINGLE_REDIRECTS = [];

for (const entry of SINGLE_REDIRECTS) {
	const matched = catchAllPrefixes.find((p) => entry.oldPath.startsWith(p + '/'));
	if (matched) {
		if (!singlesByPrefix.has(matched)) singlesByPrefix.set(matched, []);
		singlesByPrefix.get(matched)!.push(entry);
	} else {
		remainingSingles.push(entry);
	}
}

for (const group of CATCH_ALL_REDIRECTS) {
	// Single-page overrides render statically (specific paths win over the splat
	// by being earlier in the file). Exception: for empty-entry PREFIX_RENAME
	// groups the splat already maps oldPrefix/X → newPrefix/X — entries whose
	// target matches that mapping are redundant and would just duplicate the
	// splat. They still belong in redirects.json (so Astro emits dist stubs)
	// but not in _redirects.
	const overrides = singlesByPrefix.get(group.oldPrefix);
	if (overrides?.length) {
		const splatNewPrefix = group.entries.length === 0 ? group.newPrefix : null;
		for (const entry of overrides) {
			if (splatNewPrefix) {
				const rest = entry.oldPath.slice(group.oldPrefix.length + 1);
				if (entry.target === `/docs/${splatNewPrefix}/${rest}/`) continue;
			}
			staticLines.push(`/docs/${entry.oldPath}/ ${entry.target} 301`);
		}
	}

	// Empty-entry PREFIX_RENAME group — one splat rule drives the whole tree.
	if (group.entries.length === 0) {
		if (group.newPrefix) {
			autoDynamicGroups.push({
				rules: [`/docs/${group.oldPrefix}/* /docs/${group.newPrefix}/:splat 301`],
			});
		}
		continue;
	}

	// CONSOLIDATE — every entry points at the same target.
	const targets = new Set(group.entries.map((e) => e.target));
	if (targets.size === 1) {
		const target = group.entries[0].target;
		autoDynamicGroups.push({
			rules: [`/docs/${group.oldPrefix}/* ${target} 301`],
		});
		continue;
	}

	// PREFIX_RENAME with explicit entries — detect a common prefix for a splat.
	const firstEntry = group.entries[0];
	const newFull = firstEntry.target.replace(/^\/docs\//, '').replace(/\/$/, '');
	const newPrefix = newFull.slice(0, newFull.length - firstEntry.slug.length).replace(/\/$/, '');
	const allMatch = group.entries.every((e) => e.target === `/docs/${newPrefix}/${e.slug}/`);

	if (allMatch && newPrefix) {
		autoDynamicGroups.push({
			rules: [`/docs/${group.oldPrefix}/* /docs/${newPrefix}/:splat 301`],
		});
	} else {
		// Mixed targets — fall back to enumerated static rules.
		staticLines.push(`# ${group.oldPrefix} (mixed targets)`);
		for (const entry of group.entries) {
			const oldPath = entry.slug
				? `/docs/${group.oldPrefix}/${entry.slug}/`
				: `/docs/${group.oldPrefix}/`;
			staticLines.push(`${oldPath} ${entry.target} 301`);
		}
	}
}

if (remainingSingles.length > 0) {
	staticLines.push('');
	staticLines.push('# Single page redirects');
	for (const entry of remainingSingles) {
		staticLines.push(`/docs/${entry.oldPath}/ ${entry.target} 301`);
	}
}

// Non-docs rules: marketing pages, /products/*, /industries/*, external targets.
// A rule is "dynamic" only when the SOURCE has a splat or :placeholder (those
// require Cloudflare pattern matching). Literal `?query` in the target is just
// a regular static target.
const nonDocsStatic: string[] = [];
const nonDocsDynamic: string[] = [];
for (const [source, target] of Object.entries(NON_DOCS_REDIRECTS)) {
	if (source.includes('*') || /:[A-Za-z_]/.test(source)) {
		nonDocsDynamic.push(`${source} ${target} 301`);
	} else {
		nonDocsStatic.push(`${source} ${target} 301`);
	}
}
if (nonDocsStatic.length > 0) {
	staticLines.push('');
	staticLines.push('# Non-docs redirects (from NON_DOCS_REDIRECTS)');
	staticLines.push(...nonDocsStatic);
}

// DYNAMIC_REDIRECTS from redirects.ts render first in the Dynamic block so
// hand-authored patterns (blog, edge upgrade) stay at the top. Group comments
// live in the data file for maintainers; the generated file stays terse.
const manualDynamicRules = DYNAMIC_REDIRECTS.flatMap((group) =>
	group.entries.map((e) => `${e.source} ${e.target} ${e.status ?? 301}`),
);

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------

const dynamicHeader = [
	DYN_START,
	'# Must live AFTER all static rules: Cloudflare Pages starts a 100-rule',
	'# cap at the first dynamic rule, and any static rules past the cap are',
	'# silently ignored. Keeping dynamics here leaves the static zone uncapped.',
	'# Refs: https://developers.cloudflare.com/pages/configuration/redirects/',
];

// One flat block: manual rules first (blog, edge upgrade), then auto-derived
// splat rules, then non-docs rules with query/placeholder targets.
// Rules are self-describing so no comments are emitted.
const autoDynamicRules = autoDynamicGroups.flatMap((g) => g.rules);
const dynamicRules = [...manualDynamicRules, ...autoDynamicRules, ...nonDocsDynamic];

const output =
	manualHeader +
	'\n\n' +
	STATIC_START +
	'\n\n' +
	staticLines.join('\n') +
	'\n\n' +
	STATIC_END +
	'\n\n' +
	dynamicHeader.join('\n') +
	'\n\n' +
	dynamicRules.join('\n') +
	'\n';

writeFileSync(redirectsPath, output);

// Count rules directly from the written file so the report matches reality
// (includes manually-authored rules from the preserved header).
let staticRuleCount = 0;
let dynamicRuleCount = 0;
for (const line of output.split('\n')) {
	const trimmed = line.trim();
	if (!trimmed || trimmed.startsWith('#')) continue;
	const src = trimmed.split(/\s+/)[0] ?? '';
	if (src.includes('*') || /:[A-Za-z_]/.test(src)) dynamicRuleCount++;
	else staticRuleCount++;
}
console.log(
	`✓ public/_redirects — ${staticRuleCount} static + ${dynamicRuleCount} dynamic (${staticRuleCount + dynamicRuleCount} total)`,
);
