export interface UpgradeVersion {
	/** Raw version string from the YAML key, e.g. "4.3.0.1", "3.4", "3.3" */
	version: string;
	/** Display version — "4.2.0" → "4.2", otherwise same as version */
	displayVersion: string;
	/** The major.minor family, e.g. "4.3" */
	family: string;
	/** Base version for patch releases only, e.g. "4.3.0" for 4.3.0.1 */
	baseVersion?: string;
	/** CE release date string, e.g. "Feb 3 2026" */
	releaseDate: string;
	/** PE-specific release date (only if different from CE) */
	releaseDatePe?: string;
	/** "upgradable-from" value, e.g. "4.2.1.x" or "4.1.0" */
	upgradableFrom: string;
	/** Anchor of the upgradable-from version on the same platform page */
	prevVersionAnchor?: string;
	lts: boolean;
	/** true = this is a patch release within the family */
	patch: boolean;
	/** true = upgradable-from uses .x notation */
	x: boolean;
	/** false = no upgrade script needed */
	upgrade: boolean;
	/** true = pass --fromVersion to upgrade.sh */
	manualVersionUpgrade: boolean;
	/** override --fromVersion label (if different from upgradableFrom) */
	manualVersionUpgradeLabel?: string;
	/** true = Windows package is a .zip archive, not an .exe installer */
	windowsZip: boolean;
	/** Anchor ID for the version section on platform pages, e.g. "v4-3-0-1" */
	anchor: string;
	/** true = version has a known security vulnerability; excluded from the upgrade table */
	vulnerable?: boolean;
}

/** Converts a family string to a URL slug, e.g. "4.3" → "v4-3-x" */
export function getFamilySlug(family: string): string {
	return 'v' + family.replace(/\./g, '-') + '-x';
}

export const UPGRADE_VERSIONS: UpgradeVersion[] = [
	{
		version: '4.3.1.2',
		displayVersion: '4.3.1.2',
		family: '4.3',
		baseVersion: '4.3.1',
		releaseDate: 'May 28 2026',
		upgradableFrom: '4.2.1.x',
		prevVersionAnchor: 'v4-3-0-1',
		lts: true,
		patch: true,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: true,
		anchor: 'v4-3-1-2',
	},
	{
		version: '4.3.1.1',
		displayVersion: '4.3.1.1',
		family: '4.3',
		baseVersion: '4.3.1',
		releaseDate: 'Mar 31 2026',
		upgradableFrom: '4.2.1.x',
		prevVersionAnchor: 'v4-3-0-1',
		lts: true,
		patch: true,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: true,
		anchor: 'v4-3-1-1',
		vulnerable: true,
	},
	{
		version: '4.3.1',
		displayVersion: '4.3.1',
		family: '4.3',
		baseVersion: '4.3.1',
		releaseDate: 'Mar 10 2026',
		upgradableFrom: '4.2.1.x',
		prevVersionAnchor: 'v4-3-0-1',
		lts: true,
		patch: true,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: true,
		anchor: 'v4-3-1',
		vulnerable: true,
	},
	{
		version: '4.3.0.1',
		displayVersion: '4.3.0.1',
		family: '4.3',
		baseVersion: '4.3.0',
		releaseDate: 'Feb 3 2026',
		upgradableFrom: '4.2.1.x',
		prevVersionAnchor: 'v4-2-1-2',
		lts: true,
		patch: true,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v4-3-0-1',
		vulnerable: true,
	},
	{
		version: '4.2.2.2',
		displayVersion: '4.2.2.2',
		family: '4.2',
		baseVersion: '4.2.2',
		releaseDate: 'May 28 2026',
		upgradableFrom: '4.2.0',
		prevVersionAnchor: 'v4-2-1-2',
		lts: true,
		patch: true,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: true,
		anchor: 'v4-2-2-2',
	},
	{
		version: '4.2.2.1',
		displayVersion: '4.2.2.1',
		family: '4.2',
		baseVersion: '4.2.2',
		releaseDate: 'Mar 31 2026',
		upgradableFrom: '4.2.0',
		prevVersionAnchor: 'v4-2-1-2',
		lts: true,
		patch: true,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: true,
		anchor: 'v4-2-2-1',
		vulnerable: true,
	},
	{
		version: '4.2.2',
		displayVersion: '4.2.2',
		family: '4.2',
		baseVersion: '4.2.2',
		releaseDate: 'Mar 10 2026',
		upgradableFrom: '4.2.0',
		prevVersionAnchor: 'v4-2-1-2',
		lts: true,
		patch: true,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: true,
		anchor: 'v4-2-2',
		vulnerable: true,
	},
	{
		version: '4.2.1.2',
		displayVersion: '4.2.1.2',
		family: '4.2',
		baseVersion: '4.2.1',
		releaseDate: 'Feb 3 2026',
		upgradableFrom: '4.2.0',
		prevVersionAnchor: 'v4-2-0',
		lts: true,
		patch: true,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v4-2-1-2',
		vulnerable: true,
	},
	{
		version: '4.2.0',
		displayVersion: '4.2',
		family: '4.2',
		releaseDate: 'Aug 15 2025',
		upgradableFrom: '4.1.0',
		prevVersionAnchor: 'v4-1-0',
		lts: true,
		patch: false,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v4-2-0',
	},
	{
		version: '4.1.0',
		displayVersion: '4.1',
		family: '4.1',
		releaseDate: 'Jul 3 2025',
		upgradableFrom: '4.0.2',
		prevVersionAnchor: 'v4-0-2',
		lts: false,
		patch: false,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: true,
		anchor: 'v4-1-0',
	},
	{
		version: '4.0.2',
		displayVersion: '4.0.2',
		family: '4.0',
		releaseDate: 'Jul 3 2025',
		upgradableFrom: '3.9.1',
		prevVersionAnchor: 'v3-9-1',
		lts: false,
		patch: false,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: true,
		anchor: 'v4-0-2',
	},
	{
		version: '4.0.1',
		displayVersion: '4.0.1',
		family: '4.0',
		releaseDate: 'Apr 22 2025',
		upgradableFrom: '3.9.1',
		prevVersionAnchor: 'v3-9-1',
		lts: false,
		patch: false,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v4-0-1',
	},
	{
		version: '4.0.0',
		displayVersion: '4.0',
		family: '4.0',
		releaseDate: 'Apr 15 2025',
		upgradableFrom: '3.9.1',
		prevVersionAnchor: 'v3-9-1',
		lts: false,
		patch: false,
		x: true,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v4-0-0',
	},
	{
		version: '3.9.1',
		displayVersion: '3.9.1',
		family: '3.9',
		releaseDate: 'Feb 19 2025',
		upgradableFrom: '3.9.0',
		prevVersionAnchor: 'v3-9-0',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: true,
		anchor: 'v3-9-1',
	},
	{
		version: '3.9.0',
		displayVersion: '3.9',
		family: '3.9',
		releaseDate: 'Dec 31 2024',
		upgradableFrom: '3.8.1',
		prevVersionAnchor: 'v3-8-1',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		windowsZip: false,
		anchor: 'v3-9-0',
	},
	{
		version: '3.8.1',
		displayVersion: '3.8.1',
		family: '3.8',
		releaseDate: 'Oct 15 2024',
		upgradableFrom: '3.8.0',
		prevVersionAnchor: 'v3-8-0',
		lts: false,
		patch: false,
		x: false,
		upgrade: false,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-8-1',
	},
	{
		version: '3.8.0',
		displayVersion: '3.8',
		family: '3.8',
		releaseDate: 'Oct 3 2024',
		upgradableFrom: '3.7.0',
		prevVersionAnchor: 'v3-7-0',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		manualVersionUpgradeLabel: '3.7.0',
		windowsZip: false,
		anchor: 'v3-8-0',
	},
	{
		version: '3.7.0',
		displayVersion: '3.7',
		family: '3.7',
		releaseDate: 'Jun 17 2024',
		upgradableFrom: '3.6.4',
		prevVersionAnchor: 'v3-6-4',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		windowsZip: false,
		anchor: 'v3-7-0',
	},
	{
		version: '3.6.4',
		displayVersion: '3.6.4',
		family: '3.6',
		releaseDate: 'Apr 11 2024',
		upgradableFrom: '3.6.3',
		prevVersionAnchor: 'v3-6-3',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		windowsZip: false,
		anchor: 'v3-6-4',
	},
	{
		version: '3.6.3',
		displayVersion: '3.6.3',
		family: '3.6',
		releaseDate: 'Mar 18 2024',
		upgradableFrom: '3.6.2',
		prevVersionAnchor: 'v3-6-2',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		windowsZip: false,
		anchor: 'v3-6-3',
	},
	{
		version: '3.6.2',
		displayVersion: '3.6.2',
		family: '3.6',
		releaseDate: 'Dec 28 2023',
		upgradableFrom: '3.6.1',
		prevVersionAnchor: 'v3-6-1',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		windowsZip: false,
		anchor: 'v3-6-2',
	},
	{
		version: '3.6.1',
		displayVersion: '3.6.1',
		family: '3.6',
		releaseDate: 'Nov 13 2023',
		upgradableFrom: '3.6.0',
		prevVersionAnchor: 'v3-6-0',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		manualVersionUpgradeLabel: '3.6.0',
		windowsZip: false,
		anchor: 'v3-6-1',
	},
	{
		version: '3.6.0',
		displayVersion: '3.6',
		family: '3.6',
		releaseDate: 'Sep 21 2023',
		upgradableFrom: '3.5.1',
		prevVersionAnchor: 'v3-5-1',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		windowsZip: false,
		anchor: 'v3-6-0',
	},
	{
		version: '3.5.1',
		displayVersion: '3.5.1',
		family: '3.5',
		releaseDate: 'May 31 2023',
		upgradableFrom: '3.5.0',
		prevVersionAnchor: 'v3-5-0',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		manualVersionUpgradeLabel: '3.5.0',
		windowsZip: false,
		anchor: 'v3-5-1',
	},
	{
		version: '3.5.0',
		displayVersion: '3.5',
		family: '3.5',
		releaseDate: 'May 9 2023',
		upgradableFrom: '3.4.4',
		prevVersionAnchor: 'v3-4-4',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		windowsZip: false,
		anchor: 'v3-5-0',
	},
	{
		version: '3.4.4',
		displayVersion: '3.4.4',
		family: '3.4',
		releaseDate: 'Feb 7 2023',
		upgradableFrom: '3.4.3',
		prevVersionAnchor: 'v3-4-3',
		lts: false,
		patch: false,
		x: false,
		upgrade: false,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-4-4',
	},
	{
		version: '3.4.3',
		displayVersion: '3.4.3',
		family: '3.4',
		releaseDate: 'Dec 21 2022',
		upgradableFrom: '3.4.2',
		prevVersionAnchor: 'v3-4-2',
		lts: false,
		patch: false,
		x: false,
		upgrade: false,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-4-3',
	},
	{
		version: '3.4.2',
		displayVersion: '3.4.2',
		family: '3.4',
		releaseDate: 'Dec 1 2022',
		upgradableFrom: '3.4.1',
		prevVersionAnchor: 'v3-4-1',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		windowsZip: false,
		anchor: 'v3-4-2',
	},
	{
		version: '3.4.1',
		displayVersion: '3.4.1',
		family: '3.4',
		releaseDate: 'Aug 18 2022',
		upgradableFrom: '3.4.0',
		prevVersionAnchor: 'v3-4',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		manualVersionUpgradeLabel: '3.4.0',
		windowsZip: false,
		anchor: 'v3-4-1',
	},
	{
		version: '3.4',
		displayVersion: '3.4',
		family: '3.4',
		releaseDate: 'Jul 19 2022',
		upgradableFrom: '3.3.4.1',
		prevVersionAnchor: 'v3-3-4-1',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		manualVersionUpgradeLabel: '3.3.4',
		windowsZip: false,
		anchor: 'v3-4',
	},
	{
		version: '3.3.4.1',
		displayVersion: '3.3.4.1',
		family: '3.3',
		releaseDate: 'Mar 22 2022',
		releaseDatePe: 'Mar 18 2022',
		upgradableFrom: '3.3.4',
		prevVersionAnchor: 'v3-3-4',
		lts: false,
		patch: false,
		x: false,
		upgrade: false,
		manualVersionUpgrade: false,
		windowsZip: true,
		anchor: 'v3-3-4-1',
	},
	{
		version: '3.3.4',
		displayVersion: '3.3.4',
		family: '3.3',
		releaseDate: 'Mar 11 2022',
		upgradableFrom: '3.3.3',
		prevVersionAnchor: 'v3-3-3',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: true,
		windowsZip: true,
		anchor: 'v3-3-4',
	},
	{
		version: '3.3.3',
		displayVersion: '3.3.3',
		family: '3.3',
		releaseDate: 'Jan 27 2022',
		upgradableFrom: '3.3.2',
		prevVersionAnchor: 'v3-3-2',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-3-3',
	},
	{
		version: '3.3.2',
		displayVersion: '3.3.2',
		family: '3.3',
		releaseDate: 'Nov 11 2021',
		upgradableFrom: '3.3.1',
		prevVersionAnchor: 'v3-3-1',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-3-2',
	},
	{
		version: '3.3.1',
		displayVersion: '3.3.1',
		family: '3.3',
		releaseDate: 'Sep 3 2021',
		upgradableFrom: '3.3.0',
		prevVersionAnchor: 'v3-3',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-3-1',
	},
	{
		version: '3.3',
		displayVersion: '3.3',
		family: '3.3',
		releaseDate: 'Aug 13 2021',
		upgradableFrom: '3.2.2',
		prevVersionAnchor: 'v3-2-2',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-3',
	},
	{
		version: '3.2.2',
		displayVersion: '3.2.2',
		family: '3.2',
		releaseDate: 'Mar 24 2021',
		upgradableFrom: '3.2.1',
		prevVersionAnchor: 'v3-2-1',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-2-2',
	},
	{
		version: '3.2.1',
		displayVersion: '3.2.1',
		family: '3.2',
		releaseDate: 'Jan 26 2021',
		upgradableFrom: '3.2.0',
		prevVersionAnchor: 'v3-2',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-2-1',
	},
	{
		version: '3.2',
		displayVersion: '3.2',
		family: '3.2',
		releaseDate: 'Dec 1 2020',
		upgradableFrom: '3.1.1',
		prevVersionAnchor: 'v3-1-1',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-2',
	},
	{
		version: '3.1.1',
		displayVersion: '3.1.1',
		family: '3.1',
		releaseDate: 'Aug 28 2020',
		upgradableFrom: '3.1.0',
		prevVersionAnchor: 'v3-1',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-1-1',
	},
	{
		version: '3.1',
		displayVersion: '3.1',
		family: '3.1',
		releaseDate: 'Aug 12 2020',
		upgradableFrom: '3.0.1',
		prevVersionAnchor: 'v3-0-1',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-1',
	},
	{
		version: '3.0.1',
		displayVersion: '3.0.1',
		family: '3.0',
		releaseDate: 'Jun 9 2020',
		upgradableFrom: '3.0.0',
		prevVersionAnchor: 'v3-0',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-0-1',
	},
	{
		version: '3.0',
		displayVersion: '3.0',
		family: '3.0',
		releaseDate: 'Jun 1 2020',
		upgradableFrom: '2.5.6',
		lts: false,
		patch: false,
		x: false,
		upgrade: true,
		manualVersionUpgrade: false,
		windowsZip: false,
		anchor: 'v3-0',
	},
];

/** Unique version families in order, e.g. ["4.3", "4.2", "4.1", ...] */
export const UPGRADE_FAMILIES: string[] = [...new Set(UPGRADE_VERSIONS.map((v) => v.family))];
